---
deployment:
  tasks:
    - echo "Starting deployment"
    - export NODE_ENV=production
    - echo "Installing dependencies"
    - bun install
    - echo "Building project"
    - bun run build
    - echo "Clearing public_html"
    - rm -rf /home/h6idadn88wrk/public_html/*
    - echo "Copying build files"
    - cp -r dist/* /home/h6idadn88wrk/public_html/
